# Generated by Django 3.2.6 on 2021-11-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_county',
            new_name='default_state',
        ),
    ]
