# Generated by Django 3.2.6 on 2021-11-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='friendly_author_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
