# Generated by Django 3.2.6 on 2021-11-13 00:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 11, 13, 0, 2, 58, 869328, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
