# Generated by Django 3.2.6 on 2021-11-13 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='date',
        ),
    ]
