# Generated by Django 3.2.6 on 2021-11-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20211108_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='product_size',
            new_name='product_color',
        ),
    ]
