# Generated by Django 3.2.6 on 2021-11-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_rename_product_size_orderlineitem_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
