# Generated by Django 3.2.6 on 2021-11-14 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_sizes',
            new_name='has_colors',
        ),
    ]
