# Generated by Django 3.2.6 on 2021-11-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_has_sizes_product_has_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
