# Generated by Django 3.2.6 on 2021-11-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_colors',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
