# Generated by Django 3.2.6 on 2022-06-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='sku',
        ),
    ]
